#!/usr/bin/env python3
"""Generate the typed UWP TCG kernel gateway switch from KernelThunk.cpp."""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
table_path = ROOT / "src/core/kernel/exports/KernelThunk.cpp"
common_dir = ROOT / "src/core/kernel/common"
output_path = ROOT / "src/devices/x86/CxbxKernelDispatch.inc"

table = table_path.read_text(encoding="utf-8")
fastcall_names = set()
for header in common_dir.glob("*.h"):
    text = header.read_text(encoding="utf-8", errors="ignore")
    for match in re.finditer(r"EXPORTNUM\((\d+)\)(.*?);", text, re.S):
        decl = match.group(2)
        if "FASTCALL" not in decl:
            continue
        name = re.search(r"(?:KRNL\()?([A-Za-z_]\w*)\)?\s*\(", decl)
        if name:
            fastcall_names.add(name.group(1))

entries = []
for line in table.splitlines():
    ordinal_match = re.search(r"//\s+0x[0-9A-Fa-f]+\s+\((\d+)\)", line)
    if not ordinal_match or "(uintptr_t)FUNC(" not in line:
        continue
    ordinal = int(ordinal_match.group(1))
    target = re.search(r"\(uintptr_t\)FUNC\(&xbox::(.+?)\)\s*,", line)
    if not target or ordinal == 0:
        continue
    expression = target.group(1).strip()
    plain_name = re.sub(r"^KRNL\((.+)\)$", r"\1", expression)
    if ordinal in (8, 361, 362):
        entries.append(f"case {ordinal}: return InvokeKernelVarargs(call);")
    else:
        invoker = "InvokeKernelFast" if plain_name in fastcall_names else "InvokeKernel"
        entries.append(f"case {ordinal}: return {invoker}<&xbox::{expression}>(call);")

content = "// Generated by tools/generate_cxbx_kernel_dispatch.py.\n"
content += "// Do not edit by hand.\n"
content += "\n".join(entries) + "\n"
output_path.write_text(content, encoding="utf-8", newline="\n")
print(f"generated {len(entries)} kernel function gateways in {output_path}")
